### ISSUE TITLE
Power works, but not voltage and current

### ISSUE THREAD

**Issue by analystcmyk** [xeniter/WIFIPO120FWT#1]
Thank you, desoldering helped a lot in flashing indeed.

In case you followed https://zry.io/archives/799  the pin mapping for the power meter BL0937 is : 

```

CB2S => WB2S => BL0937
----------------------------
P7 => PWM1 =>CF 
P6 => PWM2 =>CF1 
P24 => PWM14 =>SEL 

```
Although Power is reported correctly, I get no values for V and I. 

Used firmware : Build on Aug 5 2022 08:18:26 version 1.12.15

Any clue?

**Comment by xeniter** [comment]
hi,

nice blog post, yes after custom command "startDriver BL0937"

i get following:
![image](https://user-images.githubusercontent.com/2132412/184534664-9a4e5ceb-2da1-4e71-8678-1c22a73971c6.png)

i assume values are bit off and needs to be calibrated, changed now to a shelly plug s which works out of box with home connect is however esp based, also i am not sure if it could measure power in the other direction (for solar)

which modul do you have? 
ELIVCO LSPA9 Smart Plug or a WIFIPO120FWT ?

**Comment by analystcmyk** [comment]
It is an ELIVCO LSPA9. I moved the issue to openbk.
